# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W3IGSITvdKjPbmjXy3yM9-KWzHk9Nurj
"""

x=7+8
y=x**2
print(x)
print(y)
